services:
  - type: web
<<<<<<< Updated upstream
<<<<<<< Updated upstream
    name: flatery-backend-render1
    env: docker
    region: singapore
    plan: free
    branch: render1
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
=======
=======
>>>>>>> Stashed changes
    name: flatery-backend
    env: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_EXPIRATION_TIME
        value: "36000000"
      - key: FRONTEND_URL
        sync: false
<<<<<<< Updated upstream
<<<<<<< Updated upstream
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
    healthCheckPath: /
=======
    healthCheckPath: /  # or /actuator/health if you use actuator
>>>>>>> Stashed changes
=======
    healthCheckPath: /  # or /actuator/health if you use actuator
>>>>>>> Stashed changes
